name: sufi-sports

services:
  customer-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sufisports-customer-web
    ports:
      - "80:80"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://127.0.0.1/ > /dev/null || exit 1" ]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 5s
    networks:
      - sufi-network

networks:
  sufi-network:
    name: sufi-network
    driver: bridge
